//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adress()
        {
            this.Zadachi = new HashSet<Zadachi>();
        }
    
        public int id { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idVar { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<System.DateTime> DataS { get; set; }
        public Nullable<System.DateTime> DateC { get; set; }
        public Nullable<decimal> Oplata { get; set; }
        public Nullable<bool> Stasus { get; set; }
        public Nullable<int> idUl { get; set; }
        public string Number { get; set; }
        public string Numberofber { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Type Type { get; set; }
        public virtual Ulitca Ulitca { get; set; }
        public virtual Var Var { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadachi> Zadachi { get; set; }
    }
}
