//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equip
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> idUs { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Usluga Usluga { get; set; }
    }
}
