//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        private static Entities _context;
        public static Entities GetContext()
        {
            if(_context == null)
            {
                _context = new Entities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Appeals> Appeals { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Equip> Equip { get; set; }
        public virtual DbSet<Roll> Roll { get; set; }
        public virtual DbSet<Sotrud> Sotrud { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Ulitca> Ulitca { get; set; }
        public virtual DbSet<Var> Var { get; set; }
        public virtual DbSet<Zadachi> Zadachi { get; set; }
    }
}
