//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrud()
        {
            this.Zadachi = new HashSet<Zadachi>();
            this.Zadachi1 = new HashSet<Zadachi>();
        }
    
        public int id { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public string FIO { get; set; }
        public string Pasport { get; set; }
        public Nullable<int> Rol { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Roll Roll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadachi> Zadachi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadachi> Zadachi1 { get; set; }
    }
}
