//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Var
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Var()
        {
            this.Adress = new HashSet<Adress>();
        }
    
        public int id { get; set; }
        public Nullable<int> FUs { get; set; }
        public Nullable<int> SUs { get; set; }
        public Nullable<int> NUs { get; set; }
        public Nullable<int> FoUs { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adress> Adress { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Usluga Usluga1 { get; set; }
        public virtual Usluga Usluga2 { get; set; }
        public virtual Usluga Usluga3 { get; set; }
    }
}
