//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadachi
    {
        public int id { get; set; }
        public Nullable<int> idSot { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> idAdr { get; set; }
        public string Discribe { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> idIsp { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Sotrud Sotrud { get; set; }
        public virtual Sotrud Sotrud1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
